### PR TITLE
Applying JPEG Quality Settings (if set in $args)

### PR DESCRIPTION
**Pull request by rpetersn**
@willmot Here's the Pull Request you noted from Issue #120 - Thx!

### CODE REVIEW

**Comment by willmot** [comment]
@joehoyle mind if I assign this over to you for a review/merge.

**Comment by joehoyle** [comment]
Need to work out why this unit test is intermittently failing, but this isn't the cause, so merging!

**Comment by joehoyle** [comment]
@rpetersn thanks!

**Comment by rpetersn** [comment]
Good deal!  Glad I could help.  Are you guys planning to push out an update to WP.org?  I'm stoked/relieved to see that you're still watching over WPThumb and keeping it alive.  I really feel like there are specific use cases where on-demand image creation is incredibly valuable and WPThumb fits the bill perfectly. Thank YOU for creating/maintaining it.

**Pull request merged**
